"""External known-answer tests for the vendored AES-256-CBC.

**Read this before adding a test here.** Round-trip tests are excluded as evidence, on
purpose. `aes.encrypt` checked against `aes.decrypt` passes even when both are wrong in
the same direction: flip a PKCS#7 pad byte, or introduce any self-cancelling transform,
and the round trip still succeeds at every length while the server rejects every body.
So each assertion below is anchored to ciphertext produced *outside* this repository,
by two mutually independent sources:

  1. `tests/fixtures/aes_kat.json` — nine plaintext lengths, ciphertext from `openssl`,
     under the *vendor's real key*, generated by `scripts/gen_aes_fixtures.sh` and
     COMMITTED. This module reads the committed file and never invokes openssl; see the
     long comment in that script for why running it at test time would be strictly worse.
  2. NIST SP 800-38A F.2.5/F.2.6 and FIPS 197 C.3 — published vectors under a *different*
     key, transcribed as literals here. They are the reason a fixture file that was
     regenerated against a subtly wrong key could not go unnoticed: the two anchors would
     then have to be wrong in the same way, under different keys, which no single bug in
     this file can arrange.

`decrypt` appears only as a SECONDARY check, always after the primary assertion that the
ciphertext matches an external answer — never as the sole evidence for a case.

Note on the NIST citation: the plan and the task brief both say "F.2.1 / F.2.2 AES-256-CBC".
That is a misnumbering — in SP 800-38A, F.2.1/F.2.2 are CBC-**AES128**.Encrypt/Decrypt;
the AES-256-CBC vectors are **F.2.5 / F.2.6**, which is what this file uses. Using
F.2.1/F.2.2 would have required teaching `aes.py` a 128-bit key schedule it has no other
reason to carry — a new, unexercised branch added purely to satisfy a citation typo.
"""

import base64
import json
from pathlib import Path

import pytest

from iparking_lib.iparking import aes, crypto

FIXTURE = Path(__file__).parent / "fixtures" / "aes_kat.json"
KAT = json.loads(FIXTURE.read_text(encoding="utf-8"))
CASES = KAT["cases"]

# --- the fixture file itself -------------------------------------------------


def test_fixture_covers_exactly_the_nine_padding_boundaries():
    """The matrix is the evidence, so its shape is itself an assertion.

    A silently shortened fixture file would make every remaining case pass while the
    boundary bug this suite exists to catch walked straight through. Each length is here
    for a distinct padding outcome: 0 empty, 16/32 a whole extra pad block, 15/31 one pad
    byte, 1/17/33 fifteen pad bytes, 47 multi-block chaining off a boundary.
    """
    assert [case["length"] for case in CASES] == [0, 1, 15, 16, 17, 31, 32, 33, 47]


def test_fixture_key_matches_the_key_the_client_actually_uses():
    """Ties the external anchor to the shipping constant.

    Without this the fixtures could be regenerated under some other key and still agree
    with an `aes.py` that had drifted the same way — the two sides of every comparison
    moving together, which is the failure mode this whole file is built to exclude.
    """
    assert bytes.fromhex(KAT["key_hex"]) == crypto.KEY
    assert bytes.fromhex(KAT["iv_hex"]) == crypto.IV
    assert bytes.fromhex(KAT["iv_hex"]) == bytes(16)


def test_fixture_records_no_ciphertext_for_a_key_of_the_wrong_size():
    assert len(crypto.KEY) == 32, "AES-256 needs a 256-bit key"


# --- primary: openssl ciphertext under the vendor key ------------------------


@pytest.mark.parametrize("case", CASES, ids=lambda c: f"len{c['length']}")
def test_encrypt_matches_openssl_ciphertext(case):
    """THE test. Our ciphertext must equal openssl's, byte for byte, at every length."""
    plaintext = bytes.fromhex(case["plaintext_hex"])
    assert len(plaintext) == case["length"]

    produced = aes.encrypt(crypto.KEY, crypto.IV, plaintext)

    assert base64.b64encode(produced).decode("ascii") == case["ciphertext_b64"]


@pytest.mark.parametrize("case", CASES, ids=lambda c: f"len{c['length']}")
def test_padded_length_matches_openssl_and_pkcs7_is_never_a_no_op(case):
    """Length alone catches the most common padding mistake without needing the bytes.

    An implementation that skips the extra block on an already-aligned input produces
    ciphertext 16 bytes shorter than openssl's at lengths 0/16/32 — and round-trips
    perfectly, because its own unpad makes the same assumption.
    """
    expected = base64.b64decode(case["ciphertext_b64"])
    padded = aes.pkcs7_pad(bytes.fromhex(case["plaintext_hex"]))

    assert len(padded) == len(expected)
    assert len(padded) > case["length"], "PKCS#7 always adds 1..16 bytes, never zero"
    assert padded[-1] == case["pad_bytes"]
    assert padded[-case["pad_bytes"] :] == bytes([case["pad_bytes"]]) * case["pad_bytes"]


@pytest.mark.parametrize("case", CASES, ids=lambda c: f"len{c['length']}")
def test_decrypt_recovers_the_plaintext_from_openssl_ciphertext(case):
    """Secondary check — decryption is driven by *openssl's* bytes, not by ours.

    This is not a round trip: the input is the committed external ciphertext, so the
    only way to pass is to invert what openssl actually did.
    """
    recovered = aes.decrypt(crypto.KEY, crypto.IV, base64.b64decode(case["ciphertext_b64"]))

    assert recovered == bytes.fromhex(case["plaintext_hex"])


def test_cbc_chains_rather_than_encrypting_each_block_independently():
    """A fixed IV makes the chaining visible in the fixtures themselves.

    Identical plaintext prefixes must share ciphertext prefixes (that is CBC with a
    constant IV — and one more reason this scheme is obfuscation, not confidentiality),
    but the block *after* the prefix must differ once the plaintext does. An ECB
    implementation mislabelled as CBC would keep both blocks identical.
    """
    by_length = {case["length"]: base64.b64decode(case["ciphertext_b64"]) for case in CASES}

    assert by_length[17][:16] == by_length[16][:16] == by_length[31][:16]
    assert by_length[17][16:32] != by_length[31][16:32]


# --- independent anchor: NIST SP 800-38A F.2.5 / F.2.6, FIPS 197 C.3 ---------

# SP 800-38A F.2.5 (CBC-AES256.Encrypt) / F.2.6 (CBC-AES256.Decrypt).
#
# DO NOT DELETE THESE AS REDUNDANT WITH THE OPENSSL FIXTURES. They are the only thing in
# the suite that can catch an ignored IV, and that was demonstrated rather than assumed:
# replacing `previous = iv` with `previous = bytes(16)` in `aes.cbc_encrypt` — i.e. dropping
# the IV entirely — leaves all nine openssl cases and every envelope test PASSING, because
# the vendor's real IV *is* sixteen zero bytes. Only `test_nist_sp800_38a_f2_5...` fails.
#
# The reason is structural, not incidental: a fixture generated under the production key
# cannot distinguish "uses the IV" from "ignores an all-zero IV". This vector's key differs
# AND its IV is non-zero, so it closes exactly the gap the other anchor cannot see.
NIST_KEY = bytes.fromhex("603deb1015ca71be2b73aef0857d77811f352c073b6108d72d9810a30914dff4")
NIST_IV = bytes.fromhex("000102030405060708090a0b0c0d0e0f")
NIST_PLAINTEXT = bytes.fromhex(
    "6bc1bee22e409f96e93d7e117393172a"
    "ae2d8a571e03ac9c9eb76fac45af8e51"
    "30c81c46a35ce411e5fbc1191a0a52ef"
    "f69f2445df4f9b17ad2b417be66c3710"
)
NIST_CIPHERTEXT = bytes.fromhex(
    "f58c4c04d6e5f1ba779eabfb5f7bfbd6"
    "9cfc4e967edb808d679f777bc6702c7d"
    "39f23369a9d9bacfa530e26304231461"
    "b2eb05e2c39be9fcda6c19078c6a9d1b"
)


def test_nist_sp800_38a_f2_5_cbc_aes256_encrypt():
    """`cbc_encrypt`, not `encrypt`: NIST's plaintext is block-aligned and UNPADDED.

    Keeping padding out of this test is what makes it a clean statement about the cipher
    and the mode. Padding is pinned separately, by the openssl fixtures above.
    """
    assert aes.cbc_encrypt(NIST_KEY, NIST_IV, NIST_PLAINTEXT) == NIST_CIPHERTEXT


def test_nist_sp800_38a_f2_6_cbc_aes256_decrypt():
    assert aes.cbc_decrypt(NIST_KEY, NIST_IV, NIST_CIPHERTEXT) == NIST_PLAINTEXT


def test_fips197_c3_aes256_single_block():
    """FIPS 197 C.3 — the bare block cipher, no mode, no padding, no IV.

    Isolates the key schedule and the round functions. When a CBC test fails this one
    says whether the fault is in the cipher or in the chaining around it, which is the
    difference between a 5-minute fix and an afternoon.
    """
    key = bytes.fromhex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
    words = aes._expand_key(key)
    plaintext = bytes.fromhex("00112233445566778899aabbccddeeff")
    expected = bytes.fromhex("8ea2b7ca516745bfeafc49904b496089")

    assert aes.encrypt_block(words, plaintext) == expected
    assert aes.decrypt_block(words, expected) == plaintext


def test_key_schedule_has_the_aes256_word_count():
    """Nr=14 ⇒ 60 words. A schedule truncated to the AES-128 length fails every vector
    above, but the count is stated here so the failure names itself."""
    assert len(aes._expand_key(crypto.KEY)) == 60


# --- rejection paths --------------------------------------------------------
#
# `pkcs7_unpad` and the CBC entry points guard the *diagnostic* decrypt path, where the
# realistic inputs are a truncated response or a body encrypted under a rotated key. They
# must raise rather than hand back something that looks like a plaintext.


def test_unpad_rejects_a_zero_pad_byte():
    """0x00 is the classic off-by-one: a pad byte written as `n-1` instead of `n`."""
    with pytest.raises(ValueError):
        aes.pkcs7_unpad(bytes(15) + bytes([0]))


def test_unpad_rejects_a_pad_byte_larger_than_a_block():
    with pytest.raises(ValueError):
        aes.pkcs7_unpad(bytes(15) + bytes([17]))


def test_unpad_rejects_inconsistent_pad_bytes():
    with pytest.raises(ValueError):
        aes.pkcs7_unpad(bytes(13) + bytes([1, 2, 3]))


def test_unpad_rejects_empty_and_misaligned_input():
    with pytest.raises(ValueError):
        aes.pkcs7_unpad(b"")
    with pytest.raises(ValueError):
        aes.pkcs7_unpad(bytes(17))


def test_cbc_rejects_a_wrong_sized_key_or_iv():
    with pytest.raises(ValueError):
        aes.cbc_encrypt(crypto.KEY[:16], crypto.IV, bytes(16))
    with pytest.raises(ValueError):
        aes.cbc_encrypt(crypto.KEY, crypto.IV[:8], bytes(16))


def test_cbc_encrypt_refuses_unpadded_input():
    """`cbc_encrypt` is the raw mode; silently padding here would make the padding
    invisible at the one call site (`aes.encrypt`) that is supposed to own it."""
    with pytest.raises(ValueError):
        aes.cbc_encrypt(crypto.KEY, crypto.IV, bytes(15))
