#!/usr/bin/env bash
#
# Regenerate the AES known-answer fixtures from `openssl`.
#
#   bash scripts/gen_aes_fixtures.sh
#
# Writes tests/fixtures/aes_kat.json and tests/fixtures/envelope_kat.json, both of
# which are COMMITTED. Run this by hand when the vendor's key or envelope shape
# changes; otherwise never.
#
# ── Why this is a separate script and not part of the test suite ────────────────
#
# The whole point of these fixtures is that the ciphertext comes from somewhere other
# than `iparking_lib/iparking/aes.py`. A test that shelled out to openssl at test time
# would depend on the very tool it is meant to be independent of: it would pass on a
# machine with a different openssl, skip on one with none, and — worst — it could not
# fail if this script's key material ever drifted from crypto.py's, because both sides
# of the comparison would move together. So the tests read the committed file and
# nothing else. If you find yourself adding a `subprocess` call to test_aes.py, stop.
#
# Round-trip tests are likewise excluded as evidence, on purpose. Our encrypt checked
# against our decrypt passes even when both are wrong in the same direction — a
# flipped PKCS#7 pad byte, or any self-cancelling transform, round-trips perfectly at
# every length. Only external ciphertext can see that.
#
# ── Why these nine plaintext lengths ───────────────────────────────────────────
#
#   0            empty input — still yields one full block of padding
#   16, 32       length ≡ 0 mod 16 → a WHOLE EXTRA BLOCK of 0x10 padding
#   15, 31       one byte of padding, the tightest case
#   1, 17, 33    fifteen bytes of padding
#   47           multi-block CBC chaining without landing on a boundary
#
# The failure this catches is quiet rather than loud. A boundary-only padding bug
# leaves login working — its body length happens to miss the boundary — and breaks
# `POST /invitations` only for plates whose JSON lands on a 16-byte multiple,
# surfacing weeks later as a baffling partial per-car result. The envelope fixtures
# below therefore include two bodies that DO land on a boundary, deliberately.
#
set -euo pipefail

cd "$(dirname "$0")/.."
mkdir -p tests/fixtures

# ASCII bytes of the key literal in the vendor's bundle: DlaCkdAnr!Qwer%@)*FronT$#~KinG!!
# Kept as hex here so this script never has to quote that string through a shell, and
# so `iparking_lib/iparking/crypto.py:KEY` and this file can be compared by eye.
# test_aes.py asserts the two agree — that check is what stops the fixtures and the
# implementation from drifting together into agreeing on the wrong answer.
KEY_HEX="446c61436b64416e7221517765722540292a46726f6e5424237e4b696e472121"
IV_HEX="00000000000000000000000000000000"

# `-K`/`-iv` given explicitly means openssl does no password derivation, so there is no
# `Salted__` header and no `-nosalt` needed. `-A` keeps the base64 on one line.
openssl_b64() {
	openssl enc -aes-256-cbc -K "$KEY_HEX" -iv "$IV_HEX" -base64 -A
}

hexdump_stdin() {
	od -An -v -tx1 | tr -d ' \n'
}

# ── tests/fixtures/aes_kat.json ────────────────────────────────────────────────

# 47 ASCII bytes; each case is the first N. Digits and lowercase letters only, so no
# byte of it can be mangled by a shell, a locale, or an editor.
PLAINTEXT="0123456789abcdef0123456789abcdef0123456789abcde"
LENGTHS=(0 1 15 16 17 31 32 33 47)

{
	printf '{\n'
	printf '  "_comment": "GENERATED by scripts/gen_aes_fixtures.sh from openssl. Do not hand-edit. Tests read this file and must never invoke openssl themselves.",\n'
	printf '  "openssl_version": "%s",\n' "$(openssl version)"
	printf '  "command": "printf %%%%s <plaintext> | openssl enc -aes-256-cbc -K %s -iv %s -base64 -A",\n' "$KEY_HEX" "$IV_HEX"
	printf '  "key_hex": "%s",\n' "$KEY_HEX"
	printf '  "iv_hex": "%s",\n' "$IV_HEX"
	printf '  "cases": [\n'
	first=1
	for length in "${LENGTHS[@]}"; do
		chunk="${PLAINTEXT:0:length}"
		hex="$(printf '%s' "$chunk" | hexdump_stdin)"
		ciphertext="$(printf '%s' "$chunk" | openssl_b64)"
		[ "$first" -eq 1 ] || printf ',\n'
		first=0
		printf '    {"length": %d, "pad_bytes": %d, "plaintext_hex": "%s", "ciphertext_b64": "%s"}' \
			"$length" "$((16 - length % 16))" "$hex" "$ciphertext"
	done
	printf '\n  ]\n}\n'
} >tests/fixtures/aes_kat.json

# ── tests/fixtures/envelope_kat.json ───────────────────────────────────────────
#
# The full wire envelope, base64(base64(ciphertext)) — the inner base64 is
# GibberishAES `enc()`, the outer is the bundle's `window.btoa(...)`.
#
# Bodies are stored as hex so no JSON quoting, and no Hangul, has to survive a trip
# through this shell. They are byte-for-byte what `JSON.stringify` produces:
# `separators=(",", ":")` and NO \uXXXX escaping.
#
# None of these carries real account data. The register bodies use `999동9999호`
# rather than the account's actual `memb_name`, which is a home address.

# 96 bytes ≡ 0 mod 16 → a whole extra padding block, on a login-shaped body.
BODY_LOGIN='{"client_id":"iparking-dev","client_pwd":"synthetic-not-a-real-password","client_os_type":"WEB"}'
# 25 bytes ≡ 9 mod 16. Isolates the Hangul question: `ensure_ascii=True` would turn
# `12가4567` into `12가4567`, changing both the bytes and the length.
BODY_PLATE='{"carNumber":"12가4567"}'
# 221 bytes ≡ 13 mod 16 — the register body from docs/RECON.md §3.
BODY_REGISTER='{"parkSeq":9001,"storSeq":100001,"userId":"iparking-dev","userName":"999동9999호","invitationDate":"20260805","invitationInfoList":[{"carNumber":"12가4567","memo":"","mobile1":"010","mobile2":"1234","mobile3":"5678"}]}'
# The same body with a 3-character memo: 224 bytes ≡ 0 mod 16. THIS is the shape of the
# bug the matrix exists for — a register body landing exactly on a block boundary.
BODY_REGISTER_ALIGNED='{"parkSeq":9001,"storSeq":100001,"userId":"iparking-dev","userName":"999동9999호","invitationDate":"20260805","invitationInfoList":[{"carNumber":"12가4567","memo":"abc","mobile1":"010","mobile2":"1234","mobile3":"5678"}]}'

emit_envelope_case() {
	local name="$1" body="$2" trailing="$3"
	local hex inner outer nbytes
	hex="$(printf '%s' "$body" | hexdump_stdin)"
	# Byte length from the hex, NOT from `${#body}` — in a UTF-8 locale bash counts
	# characters, so every Hangul body would be reported three bytes short per syllable
	# and the "≡ 0 mod 16" annotations would be fiction.
	nbytes=$((${#hex} / 2))
	# Command substitution strips the trailing newline openssl writes, so the outer
	# base64 encodes the base64 TEXT only. Leave the newline in and every envelope
	# here is wrong by four characters.
	inner="$(printf '%s' "$body" | openssl_b64)"
	outer="$(printf '%s' "$inner" | openssl base64 -A)"
	printf '    {"name": "%s", "body_len": %d, "body_len_mod_16": %d, "body_json_hex": "%s", "inner_b64": "%s", "envelope": "%s"}%s\n' \
		"$name" "$nbytes" "$((nbytes % 16))" "$hex" "$inner" "$outer" "$trailing"
}

{
	printf '{\n'
	printf '  "_comment": "GENERATED by scripts/gen_aes_fixtures.sh from openssl. envelope = base64(base64(AES-256-CBC(PKCS#7(body)))) — the inner base64 is GibberishAES enc(), the outer is the bundle window.btoa(). Tests read this file and must never invoke openssl themselves.",\n'
	printf '  "openssl_version": "%s",\n' "$(openssl version)"
	printf '  "command": "inner=$(printf %%%%s <body> | openssl enc -aes-256-cbc -K %s -iv %s -base64 -A); printf %%%%s $inner | openssl base64 -A",\n' "$KEY_HEX" "$IV_HEX"
	printf '  "key_hex": "%s",\n' "$KEY_HEX"
	printf '  "iv_hex": "%s",\n' "$IV_HEX"
	printf '  "cases": [\n'
	emit_envelope_case "login" "$BODY_LOGIN" ","
	emit_envelope_case "plate_hangul" "$BODY_PLATE" ","
	emit_envelope_case "register" "$BODY_REGISTER" ","
	emit_envelope_case "register_block_aligned" "$BODY_REGISTER_ALIGNED" ""
	printf '  ]\n}\n'
} >tests/fixtures/envelope_kat.json

printf 'wrote tests/fixtures/aes_kat.json (%d cases)\n' "${#LENGTHS[@]}"
printf 'wrote tests/fixtures/envelope_kat.json (4 cases)\n'
